//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consumir.ServicioOwncloud {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="oc_users", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class oc_users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string displaynameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string uidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string displayname {
            get {
                return this.displaynameField;
            }
            set {
                if ((object.ReferenceEquals(this.displaynameField, value) != true)) {
                    this.displaynameField = value;
                    this.RaisePropertyChanged("displayname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                if ((object.ReferenceEquals(this.uidField, value) != true)) {
                    this.uidField = value;
                    this.RaisePropertyChanged("uid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="oc_share", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class oc_share : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short acceptedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> expirationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> file_sourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string file_targetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string item_sourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string item_targetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string item_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short mail_sendField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> parentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short permissionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short share_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string share_withField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long stimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string uid_ownerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short accepted {
            get {
                return this.acceptedField;
            }
            set {
                if ((this.acceptedField.Equals(value) != true)) {
                    this.acceptedField = value;
                    this.RaisePropertyChanged("accepted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> expiration {
            get {
                return this.expirationField;
            }
            set {
                if ((this.expirationField.Equals(value) != true)) {
                    this.expirationField = value;
                    this.RaisePropertyChanged("expiration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> file_source {
            get {
                return this.file_sourceField;
            }
            set {
                if ((this.file_sourceField.Equals(value) != true)) {
                    this.file_sourceField = value;
                    this.RaisePropertyChanged("file_source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string file_target {
            get {
                return this.file_targetField;
            }
            set {
                if ((object.ReferenceEquals(this.file_targetField, value) != true)) {
                    this.file_targetField = value;
                    this.RaisePropertyChanged("file_target");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string item_source {
            get {
                return this.item_sourceField;
            }
            set {
                if ((object.ReferenceEquals(this.item_sourceField, value) != true)) {
                    this.item_sourceField = value;
                    this.RaisePropertyChanged("item_source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string item_target {
            get {
                return this.item_targetField;
            }
            set {
                if ((object.ReferenceEquals(this.item_targetField, value) != true)) {
                    this.item_targetField = value;
                    this.RaisePropertyChanged("item_target");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string item_type {
            get {
                return this.item_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.item_typeField, value) != true)) {
                    this.item_typeField = value;
                    this.RaisePropertyChanged("item_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short mail_send {
            get {
                return this.mail_sendField;
            }
            set {
                if ((this.mail_sendField.Equals(value) != true)) {
                    this.mail_sendField = value;
                    this.RaisePropertyChanged("mail_send");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> parent {
            get {
                return this.parentField;
            }
            set {
                if ((this.parentField.Equals(value) != true)) {
                    this.parentField = value;
                    this.RaisePropertyChanged("parent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short permissions {
            get {
                return this.permissionsField;
            }
            set {
                if ((this.permissionsField.Equals(value) != true)) {
                    this.permissionsField = value;
                    this.RaisePropertyChanged("permissions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short share_type {
            get {
                return this.share_typeField;
            }
            set {
                if ((this.share_typeField.Equals(value) != true)) {
                    this.share_typeField = value;
                    this.RaisePropertyChanged("share_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string share_with {
            get {
                return this.share_withField;
            }
            set {
                if ((object.ReferenceEquals(this.share_withField, value) != true)) {
                    this.share_withField = value;
                    this.RaisePropertyChanged("share_with");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long stime {
            get {
                return this.stimeField;
            }
            set {
                if ((this.stimeField.Equals(value) != true)) {
                    this.stimeField = value;
                    this.RaisePropertyChanged("stime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenField, value) != true)) {
                    this.tokenField = value;
                    this.RaisePropertyChanged("token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string uid_owner {
            get {
                return this.uid_ownerField;
            }
            set {
                if ((object.ReferenceEquals(this.uid_ownerField, value) != true)) {
                    this.uid_ownerField = value;
                    this.RaisePropertyChanged("uid_owner");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="oc_filecache", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class oc_filecache : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int encryptedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string etagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int fileidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int mimepartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int mimetypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int mtimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int parentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string path_hashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> permissionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long sizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int storageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int storage_mtimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long unencrypted_sizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int encrypted {
            get {
                return this.encryptedField;
            }
            set {
                if ((this.encryptedField.Equals(value) != true)) {
                    this.encryptedField = value;
                    this.RaisePropertyChanged("encrypted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string etag {
            get {
                return this.etagField;
            }
            set {
                if ((object.ReferenceEquals(this.etagField, value) != true)) {
                    this.etagField = value;
                    this.RaisePropertyChanged("etag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int fileid {
            get {
                return this.fileidField;
            }
            set {
                if ((this.fileidField.Equals(value) != true)) {
                    this.fileidField = value;
                    this.RaisePropertyChanged("fileid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int mimepart {
            get {
                return this.mimepartField;
            }
            set {
                if ((this.mimepartField.Equals(value) != true)) {
                    this.mimepartField = value;
                    this.RaisePropertyChanged("mimepart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int mimetype {
            get {
                return this.mimetypeField;
            }
            set {
                if ((this.mimetypeField.Equals(value) != true)) {
                    this.mimetypeField = value;
                    this.RaisePropertyChanged("mimetype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int mtime {
            get {
                return this.mtimeField;
            }
            set {
                if ((this.mtimeField.Equals(value) != true)) {
                    this.mtimeField = value;
                    this.RaisePropertyChanged("mtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int parent {
            get {
                return this.parentField;
            }
            set {
                if ((this.parentField.Equals(value) != true)) {
                    this.parentField = value;
                    this.RaisePropertyChanged("parent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string path {
            get {
                return this.pathField;
            }
            set {
                if ((object.ReferenceEquals(this.pathField, value) != true)) {
                    this.pathField = value;
                    this.RaisePropertyChanged("path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string path_hash {
            get {
                return this.path_hashField;
            }
            set {
                if ((object.ReferenceEquals(this.path_hashField, value) != true)) {
                    this.path_hashField = value;
                    this.RaisePropertyChanged("path_hash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> permissions {
            get {
                return this.permissionsField;
            }
            set {
                if ((this.permissionsField.Equals(value) != true)) {
                    this.permissionsField = value;
                    this.RaisePropertyChanged("permissions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long size {
            get {
                return this.sizeField;
            }
            set {
                if ((this.sizeField.Equals(value) != true)) {
                    this.sizeField = value;
                    this.RaisePropertyChanged("size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int storage {
            get {
                return this.storageField;
            }
            set {
                if ((this.storageField.Equals(value) != true)) {
                    this.storageField = value;
                    this.RaisePropertyChanged("storage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int storage_mtime {
            get {
                return this.storage_mtimeField;
            }
            set {
                if ((this.storage_mtimeField.Equals(value) != true)) {
                    this.storage_mtimeField = value;
                    this.RaisePropertyChanged("storage_mtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long unencrypted_size {
            get {
                return this.unencrypted_sizeField;
            }
            set {
                if ((this.unencrypted_sizeField.Equals(value) != true)) {
                    this.unencrypted_sizeField = value;
                    this.RaisePropertyChanged("unencrypted_size");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="oc_storages", Namespace="http://schemas.datacontract.org/2004/07/Entities")]
    [System.SerializableAttribute()]
    public partial class oc_storages : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numeric_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numeric_id {
            get {
                return this.numeric_idField;
            }
            set {
                if ((this.numeric_idField.Equals(value) != true)) {
                    this.numeric_idField = value;
                    this.RaisePropertyChanged("numeric_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioOwncloud.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateUser", ReplyAction="http://tempuri.org/IService1/CreateUserResponse")]
        bool CreateUser(consumir.ServicioOwncloud.oc_users entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateUser", ReplyAction="http://tempuri.org/IService1/CreateUserResponse")]
        System.Threading.Tasks.Task<bool> CreateUserAsync(consumir.ServicioOwncloud.oc_users entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUser", ReplyAction="http://tempuri.org/IService1/UpdateUserResponse")]
        bool UpdateUser(consumir.ServicioOwncloud.oc_users entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUser", ReplyAction="http://tempuri.org/IService1/UpdateUserResponse")]
        System.Threading.Tasks.Task<bool> UpdateUserAsync(consumir.ServicioOwncloud.oc_users entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUser", ReplyAction="http://tempuri.org/IService1/DeleteUserResponse")]
        bool DeleteUser(string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUser", ReplyAction="http://tempuri.org/IService1/DeleteUserResponse")]
        System.Threading.Tasks.Task<bool> DeleteUserAsync(string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListUser", ReplyAction="http://tempuri.org/IService1/ListUserResponse")]
        consumir.ServicioOwncloud.oc_users[] ListUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListUser", ReplyAction="http://tempuri.org/IService1/ListUserResponse")]
        System.Threading.Tasks.Task<consumir.ServicioOwncloud.oc_users[]> ListUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchUser", ReplyAction="http://tempuri.org/IService1/SearchUserResponse")]
        consumir.ServicioOwncloud.oc_users SearchUser(string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchUser", ReplyAction="http://tempuri.org/IService1/SearchUserResponse")]
        System.Threading.Tasks.Task<consumir.ServicioOwncloud.oc_users> SearchUserAsync(string uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateShare", ReplyAction="http://tempuri.org/IService1/CreateShareResponse")]
        bool CreateShare(consumir.ServicioOwncloud.oc_share entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateShare", ReplyAction="http://tempuri.org/IService1/CreateShareResponse")]
        System.Threading.Tasks.Task<bool> CreateShareAsync(consumir.ServicioOwncloud.oc_share entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateShare", ReplyAction="http://tempuri.org/IService1/UpdateShareResponse")]
        bool UpdateShare(consumir.ServicioOwncloud.oc_share entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateShare", ReplyAction="http://tempuri.org/IService1/UpdateShareResponse")]
        System.Threading.Tasks.Task<bool> UpdateShareAsync(consumir.ServicioOwncloud.oc_share entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteShare", ReplyAction="http://tempuri.org/IService1/DeleteShareResponse")]
        bool DeleteShare(string share_with, string file_target);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteShare", ReplyAction="http://tempuri.org/IService1/DeleteShareResponse")]
        System.Threading.Tasks.Task<bool> DeleteShareAsync(string share_with, string file_target);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListShare", ReplyAction="http://tempuri.org/IService1/ListShareResponse")]
        consumir.ServicioOwncloud.oc_share[] ListShare();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListShare", ReplyAction="http://tempuri.org/IService1/ListShareResponse")]
        System.Threading.Tasks.Task<consumir.ServicioOwncloud.oc_share[]> ListShareAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListFileCache", ReplyAction="http://tempuri.org/IService1/ListFileCacheResponse")]
        consumir.ServicioOwncloud.oc_filecache[] ListFileCache();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListFileCache", ReplyAction="http://tempuri.org/IService1/ListFileCacheResponse")]
        System.Threading.Tasks.Task<consumir.ServicioOwncloud.oc_filecache[]> ListFileCacheAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListStorage", ReplyAction="http://tempuri.org/IService1/ListStorageResponse")]
        consumir.ServicioOwncloud.oc_storages[] ListStorage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListStorage", ReplyAction="http://tempuri.org/IService1/ListStorageResponse")]
        System.Threading.Tasks.Task<consumir.ServicioOwncloud.oc_storages[]> ListStorageAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : consumir.ServicioOwncloud.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<consumir.ServicioOwncloud.IService1>, consumir.ServicioOwncloud.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CreateUser(consumir.ServicioOwncloud.oc_users entity) {
            return base.Channel.CreateUser(entity);
        }
        
        public System.Threading.Tasks.Task<bool> CreateUserAsync(consumir.ServicioOwncloud.oc_users entity) {
            return base.Channel.CreateUserAsync(entity);
        }
        
        public bool UpdateUser(consumir.ServicioOwncloud.oc_users entity) {
            return base.Channel.UpdateUser(entity);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateUserAsync(consumir.ServicioOwncloud.oc_users entity) {
            return base.Channel.UpdateUserAsync(entity);
        }
        
        public bool DeleteUser(string uid) {
            return base.Channel.DeleteUser(uid);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUserAsync(string uid) {
            return base.Channel.DeleteUserAsync(uid);
        }
        
        public consumir.ServicioOwncloud.oc_users[] ListUser() {
            return base.Channel.ListUser();
        }
        
        public System.Threading.Tasks.Task<consumir.ServicioOwncloud.oc_users[]> ListUserAsync() {
            return base.Channel.ListUserAsync();
        }
        
        public consumir.ServicioOwncloud.oc_users SearchUser(string uid) {
            return base.Channel.SearchUser(uid);
        }
        
        public System.Threading.Tasks.Task<consumir.ServicioOwncloud.oc_users> SearchUserAsync(string uid) {
            return base.Channel.SearchUserAsync(uid);
        }
        
        public bool CreateShare(consumir.ServicioOwncloud.oc_share entity) {
            return base.Channel.CreateShare(entity);
        }
        
        public System.Threading.Tasks.Task<bool> CreateShareAsync(consumir.ServicioOwncloud.oc_share entity) {
            return base.Channel.CreateShareAsync(entity);
        }
        
        public bool UpdateShare(consumir.ServicioOwncloud.oc_share entity) {
            return base.Channel.UpdateShare(entity);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateShareAsync(consumir.ServicioOwncloud.oc_share entity) {
            return base.Channel.UpdateShareAsync(entity);
        }
        
        public bool DeleteShare(string share_with, string file_target) {
            return base.Channel.DeleteShare(share_with, file_target);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteShareAsync(string share_with, string file_target) {
            return base.Channel.DeleteShareAsync(share_with, file_target);
        }
        
        public consumir.ServicioOwncloud.oc_share[] ListShare() {
            return base.Channel.ListShare();
        }
        
        public System.Threading.Tasks.Task<consumir.ServicioOwncloud.oc_share[]> ListShareAsync() {
            return base.Channel.ListShareAsync();
        }
        
        public consumir.ServicioOwncloud.oc_filecache[] ListFileCache() {
            return base.Channel.ListFileCache();
        }
        
        public System.Threading.Tasks.Task<consumir.ServicioOwncloud.oc_filecache[]> ListFileCacheAsync() {
            return base.Channel.ListFileCacheAsync();
        }
        
        public consumir.ServicioOwncloud.oc_storages[] ListStorage() {
            return base.Channel.ListStorage();
        }
        
        public System.Threading.Tasks.Task<consumir.ServicioOwncloud.oc_storages[]> ListStorageAsync() {
            return base.Channel.ListStorageAsync();
        }
    }
}
